// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajibbbvdxysgztmlltzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqaWJiYnZkeHlzZ3p0bWxsdHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjA5NzMsImV4cCI6MjA2NTU5Njk3M30.TMK4znl083RtzXukXX4N8a0cUCyzqIrkNk7KO5sMtig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);